name: Run Task 8 Controller and Use Case Tests

on:
  push:
    branches:
      - main  # Adjust to the branch you want to track
  pull_request:
    branches:
      - main  # Adjust as necessary

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0' # Replace with your Go version

      - name: Install dependencies
        working-directory: ./task-8
        run: go mod download

      - name: Run Task 8 Controller Tests
        working-directory: ./task-8
        run: go test ./tests/controller_tests/...

      - name: Run Task 8 Use Case Tests
        working-directory: ./task-8
        run: go test ./tests/usecase_tests/...
